// Generated by CoffeeScript 1.4.0
(function() {
  var ISBNRegexp, bookParamsTable, bookParamsTableParams, isbn, param, xhr, _i, _len;

  bookParamsTable = document.querySelector('#all-params tbody');

  bookParamsTableParams = document.querySelectorAll('#all-params td');

  ISBNRegexp = /(\s)*[0-9]+[- ][0-9]+[- ][0-9]+[- ][0-9]*[- ]*[xX0-9]/;

  isbn = null;

  for (_i = 0, _len = bookParamsTableParams.length; _i < _len; _i++) {
    param = bookParamsTableParams[_i];
    param = param.innerHTML;
    if (ISBNRegexp.test(param)) {
      isbn = param.replace(/-/g, '');
    }
  }

  if (isbn) {
    xhr = new XMLHttpRequest();
    xhr.open("GET", "https://www.goodreads.com/book/review_counts.json?isbns=" + isbn + "&key=iCKldysmu9HEvXtDrUYw", true);
    xhr.onreadystatechange = function() {
      var a, book, books, id, rating, td, th, tr, votes;
      if (xhr.readyState === 4) {
        books = JSON.parse(xhr.responseText).books;
        if (books) {
          book = books[0];
          id = book.id;
          votes = book.work_ratings_count;
          rating = book.average_rating;
          tr = document.createElement("tr");
          th = document.createElement("th");
          th.appendChild(document.createTextNode("Goodreads рейтинг: "));
          td = document.createElement("td");
          a = document.createElement("a");
          a.href = "https://www.goodreads.com/book/show/" + id;
          a.appendChild(document.createTextNode("" + rating + " (всего " + votes + " голосов)"));
          td.appendChild(a);
          tr.appendChild(th);
          tr.appendChild(td);
          return bookParamsTable.insertBefore(tr, bookParamsTable.querySelector('.goods_social_btn'));
        }
      }
    };
    xhr.send();
  }

}).call(this);
